## Creating 1-D Array

In [4]:
import numpy as np

myarray= np.array(["Akhil","Athira","Anju"])

In [24]:
print(myarray)

['Akhil' 'Athira' 'Anju']


In [28]:
myarray1= np.array([1,2,3,4,5],int)

In [38]:
myarray5=myarray.copy() # .copy()  
myarray5

array(['Akhil', 'Athira', 'Anju'], dtype='<U6')

In [40]:
myarray6=myarray1.view() # .view()  function to create new array from existing array 
myarray6

array([1, 2, 3, 4, 5])

In [44]:
myarray6=np.arange(15) # creating integer using arange function
myarray6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [50]:
myarray7=np.arange(5,10, dtype=float)
myarray7

array([5., 6., 7., 8., 9.])

In [9]:
myarray8=np.linspace(12,24,6,dtype=int)
myarray8

array([12, 14, 16, 19, 21, 24])

In [66]:
myarray9=np.zeros(4)
myarray9

array([0., 0., 0., 0.])

In [70]:
np.min(myarray9)

0.0

In [73]:
myarray8.min()

12

In [42]:
myarray8+10 # mathematicaly adding an element to whole arrays

array([22, 24, 26, 29, 31, 34])

In [52]:
myarray8[0]=20
myarray8

array([20, 14, 16, 19, 21, 24])

AttributeError: 'numpy.ndarray' object has no attribute 'extend'